/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.farmtotablenetwork.ui.farm;
import com.mycompany.farmtotablenetwork.ConfigureABusiness;
import com.mycompany.farmtotablenetwork.ui.*;
import com.mycompany.farmtotablenetwork.ui.main.CardSequencePanel;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author p.starobinets
 */
public class NewCropPanel extends JPanel {
    private final CardSequencePanel cardPanel;
    private final FarmerWorkArea parent;
    private JTextField fieldType;
    private JTextField fieldLocation;
    private JTextField fieldDate;
    private JLabel errorLabel;
    
    public NewCropPanel(CardSequencePanel cardPanel, FarmerWorkArea parent){
        this.cardPanel = cardPanel;
        this.parent = parent;
        setLayout(new BorderLayout());
        setBackground(UIConstants.BG_APP);
        buildUI();
    }

    private void buildUI() {
        //-------NORTH------- means top of thepage aka header        
        
        add(UIFactory.headerSimple("New Crop"), BorderLayout.NORTH); //calls a factory method that returns a pre-styled header and places it at the top (NORTH)
       
        //forms decorative padding around the form area start block
        JPanel formOuter = new JPanel(new BorderLayout()); 
        formOuter.setBackground(UIConstants.BG_APP);
        formOuter.setBorder(BorderFactory.createEmptyBorder(
            UIConstants.PADDING, UIConstants.PADDING * 3,
            UIConstants.PADDING, UIConstants.PADDING * 3));
        //end of padding block
        
        
        //this block adds a "card" -  a container inside which fields of the form may be added
        JPanel card = new JPanel(new GridBagLayout());  //this layout lets you place components row by row with alignment control
        card.setBackground(UIConstants.BG_PANEL);
        card.setBorder(BorderFactory.createCompoundBorder(   //this adds 2 decorative borders - the outer line and the inner padding
            BorderFactory.createLineBorder(UIConstants.BORDER_LIGHT),
            BorderFactory.createEmptyBorder(UIConstants.PADDING, UIConstants.PADDING,
                                            UIConstants.PADDING, UIConstants.PADDING)));

        //------ CENTER----- middle of the panel where the form goes
        
        //gbc is the ruleset that tells GridBagLayout where to place the components
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(6, 8, 6, 8);  //insets are spacing around each cell
        gbc.anchor = GridBagConstraints.WEST;  //anchor west means snap to the left side

        //adding the section divider
        int row = 0;
        gbc.gridx = 0; gbc.gridy = row++; gbc.gridwidth = 2; gbc.fill = GridBagConstraints.HORIZONTAL;
        card.add(UIFactory.sectionDivider("Crop Details"), gbc);
        gbc.gridwidth = 1;
        //gridx means starts at column 0, gridy = row++ places at current row and increments row for the next component
        //gridwidth = 2 makes this component span both columns

        
        //begin Input fields
        //UIFactory.labelField adds a label to column 0, adds JTextField to column 1, wires up the gbc positioning, returns JTextField
        
        fieldType     = UIFactory.labeledField(card, gbc, "Crop Type *",     row++);
        fieldLocation = UIFactory.labeledField(card, gbc, "Field Location *", row++);
        fieldDate     = UIFactory.labeledField(card, gbc, "Planting Date * (YYYY-MM-DD)", row++);
        gbc.gridx = 0; gbc.gridy = row++; gbc.gridwidth = 2; 

        //Vertical glue wihout this block it would bunch all rows together at the top
        //Instead invisible spacer row absorbs all leftover vertical space
        gbc.weighty = 1; gbc.fill = GridBagConstraints.BOTH;
        card.add(Box.createVerticalGlue(), gbc);
        gbc.weighty = 0;
        
        gbc.gridx = 0; gbc.gridy = row++; gbc.gridwidth = 2; gbc.fill = GridBagConstraints.HORIZONTAL;

        //starts blank but is used for error messages that could be generated by validateInputs()
        errorLabel = UIFactory.errorLabel();
        card.add(errorLabel, gbc);

        
        //this block wraps the card in a scroll pane
        formOuter.add(card, BorderLayout.CENTER);
        JScrollPane scroll = new JScrollPane(formOuter);
        scroll.setBorder(null);

        scroll.getViewport().setBackground(UIConstants.BG_APP);
        add(scroll, BorderLayout.CENTER);

        
        //------SOUTH----- The button bar section
        JPanel btnBar = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, UIConstants.PADDING));   //aligns buttons on the right side
        btnBar.setBackground(UIConstants.BG_APP);
        btnBar.setBorder(BorderFactory.createMatteBorder(1, 0, 0, 0, UIConstants.BORDER_LIGHT));

        JButton btnBack   = UIFactory.secondaryButton("← Back");
        JButton btnSubmit = UIFactory.primaryButton("Save Crop");

        btnBack.addActionListener(e   -> popPanel());
        btnSubmit.addActionListener(e -> onSubmit());
        btnBar.add(btnBack);
        btnBar.add(btnSubmit);
        add(btnBar, BorderLayout.SOUTH);
    }
    
    //runs basic validations   
     private boolean validateInputs() {
        if (fieldType.getText().trim().isEmpty()) {
            errorLabel.setText("⚠ Crop Type is required.");
            return false;
        }
        
        if (fieldLocation.getText().trim().isEmpty()) {
            errorLabel.setText("⚠ Field Location is required.");
            return false;
        }
        
        if (!fieldDate.getText().trim().matches("\\d{4}-\\d{2}-\\d{2}")) {
            errorLabel.setText("⚠ Date must be YYYY-MM-DD.");
            return false;
        }

        errorLabel.setText(" ");
        return true;
    }

     //cretaes new crop andreturns to Farmer Work Area
    private void onSubmit() {
        if (!validateInputs()) return;
    ConfigureABusiness.cropDirectory.newCrop(
        fieldType.getText().trim(),
        fieldDate.getText().trim(),
        fieldLocation.getText().trim()
    );
    parent.loadTable();

    // Show success, then reset fields for another entry
    JOptionPane.showMessageDialog(
        this,
        "Crop saved successfully.",
        "Success",
        JOptionPane.INFORMATION_MESSAGE
    );

    fieldType.setText("");
    fieldLocation.setText("");
    fieldDate.setText("");
    errorLabel.setText(" ");
    fieldType.requestFocusInWindow();
    }

    //"Back button" navigation
    private void popPanel() {
        cardPanel.popPanel(this);
    }

}


